### PR TITLE
Fixing the possible memory leak in stream of messages

### PR DESCRIPTION
**Pull request by lhenriquegomescamilo**
### chat.component.ts 
According to the documentation of angular, it's a great ideia make the unsubscribe on method hook **ngOnDestroy**, or use the async pipe and handle events from streams.

* To more information about the memory leak look this articles:
   * https://itnext.io/angular-rxjs-detecting-memory-leaks-bdd312a070a0
   * https://www.twilio.com/blog/prevent-memory-leaks-angular-observable-ngondestroy

### socket.service.ts 
* Using methods from rxjs to listem event from socket.io

### CODE REVIEW

**Comment by luixaviles** [comment]
Hi @lhenriquegomescamilo, sorry for the late reply. I love the proposal to fix possible memory leaks.
I just updated the project to the latest versions and I see more changes than needed in your PR.
May you update your code with the latest code and send it again, please?

**Comment by lhenriquegomescamilo** [comment]
> Hi @lhenriquegomescamilo, sorry for the late reply. I love the proposal to fix possible memory leaks.
> I just updated the project to the latest versions and I see more changes than needed in your PR.
> May you update your code with the latest code and send it again, please?

Yes, of course, thank you for encouraging me to update. I'll like to fix these conflicting files as possible.

**Comment by lhenriquegomescamilo** [comment]
Hi @luixaviles, sorry for my late answer and finally I updated this pull request!  Tell me what do you think about these fixes!

**Comment by luixaviles** [comment]
Hi, @lhenriquegomescamilo  I saw several changes in your PR. I cannot merge this since most of your code is already in the master branch.
Since you will have a lot of conflicts here, I suggest creating a brand new PR from a new branch with your code only.

**Comment by lhenriquegomescamilo** [comment]
Ok... no problems 🙂

**Pull request closed without merging**
