### PR TITLE
Made Service to store and get stored username

### PR DESCRIPTION
**Pull request by harshilparmar**
I just made service for solving issue #34 

Thanks!! please let me know if I am wrong!!

### CODE REVIEW

**Review by luixaviles — APPROVED** [review]

**Comment by luixaviles** [comment]
Looks good to me, thanks for the contribution!

**Comment by luixaviles** [comment]
Closes #34

**Comment by harshilparmar** [comment]
@luixaviles Thanks!!! Sir this is the best way to right code using typescript in node.js am I right? 
Can I use same coding style for my company project?

**Comment by luixaviles** [comment]
If you have experience with Angular, I can suggest you can take a look at @nestjs.

**Pull request merged**
