### PR TITLE
Update to reload files after change via nodemon and gulp

### PR DESCRIPTION
**Pull request by headwinds**
I've added the ability to watch the typescript files and reload them when changed. 

sorry (not sorry) that chat-server.ts got whacked by Prettier - hope that's ok - as a python dev, I also get caught leaving 4 instead of 2 spaces on ;-D

### CODE REVIEW

**Comment by xinthose** [comment]
I like that you added CORS.

**Comment by luixaviles** [comment]
I love your changes @headwinds. However, I think it should be better to add this code as documentation to allow add live-reload support on server side. 
May you add your `gulpfile.js`, `nodemon.json` and new modules for your `package.json` please? 
I just created a new wiki page for this purpose: [https://github.com/luixaviles/socket-io-typescript-chat/wiki/Adding-live-reload-to-nodejs-server](https://github.com/luixaviles/socket-io-typescript-chat/wiki/Adding-live-reload-to-nodejs-server)

The main reason to do this is to keep the server-side as simple as possible. Does that sound good to you?

**Comment by luixaviles** [comment]
On another hand, it looks interesting to add `Prettier` support on the client and the server. Also, `CORS` support can be added as another PR.

**Comment by headwinds** [comment]
@xinthose @luixaviles 

I can understand why you’d want to keep it simple as a teaching tool, but these updates don’t really make the server that much more complicated. You will inevitably run into these issues when you go to deploy and adding libraries like cors attempt to solve production problems regarding client to server communication. 

I’m mainly interested helping devs deploy both client and server into the cloud. In 2018, when I first contributed to this project, I could use Zeit to deploy both since, at that time, they ran the server in a docker container. Not anymore.

Today, in the age of serverless, it’s no longer possible. Netlify and Zeit don’t support socket.io - it seems Heroku is the only option for a dev does not want to toil on backend configuration and roll their own using Digital Ocean. 

[Zeit actually recommends using Pusher](https://zeit.co/guides/deploying-pusher-channels-with-zeit-now) instead of socket.io even though their CEO is a core contributor of socket.io so I bet we’ll see support in the future just not today. 

I spent about 2 hours yesterday attempting to deploy the sever to Zeit. The browser complained about cors errors as a red herring even though I had added cors support which should have worked. It’s only until I googled “zeit socket.io” that I learned the reality. Noting this issue could save another dev the pain I faced. Still, with any pain, I did learn quite a bit about the state of serverless and how lamdba functions aren't made for web sockets. 

It’s cool (and a bit weird) that you’re only interested in parts of this update since I’ve done nothing to break the experience and, in my mind, this work only makes it better especially now that nodemon watches the typescript files and reloads the server automatically whenever you save. 

Would re-consider this complete solution? Did you try to run it?  I just don’t see how providing a folder with pieces of the solution are that helpful.

Perhaps, as you suggest, a wiki post would be the best way forward to share this experimental work. I've basically just written one 😅

**Comment by luixaviles** [comment]
I agree with you, let's move forward with your PR. Can you fix the conflicts and make sure you have the latest code version?
Also, It would be great to have some notes on the Readme file to run `gulp serve` as another option to have live-reload using nodemon.

**Comment by headwinds** [comment]
@luixaviles I actually fixed the conflicts before I commented ;-D I pulled up upstream master and merged the latest. 

I'll add some documentation to the readme though.

**Comment by headwinds** [comment]
@luixaviles I've updated the readme and the [wiki](https://github.com/luixaviles/socket-io-typescript-chat/wiki/Server-Deployment) including a note about Zeit's version 1 v 2 support for socket.io and how to follow their progress towards eventually adding it.

**Comment by luixaviles** [comment]
Closes #17

**Comment by xinthose** [comment]
We needed `es6` support anyway.  `npm upgrade` broke the server when using `es5` from an older version of this project.

**Pull request merged**
